name: Changesets

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-versions:
    name: ⚙️ Variables Setup
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.var.outputs.node-version }}
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: package.json
          branch: ${{ github.ref }}

      - id: var
        run: |
          NODE_VERSION=$(node -p "require('./package.json').engines.node")
          echo "NODE_VERSION: ${NODE_VERSION}"
          echo "node-version=${NODE_VERSION}" >> $GITHUB_OUTPUT

  release:
    name: Release
    needs: [release-versions]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ needs.release-versions.outputs.node-version }}
          cache-modules: true
          install: true

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: 'chore: Bump packages'
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
